kind: Service
apiVersion: v1
metadata: 
  name: nginx-lb
spec: 
  type: LoadBalancer
  selector: #Labels are used as seletors
    project: expense
    component: backend
    environment: dev
    version: "1.0.0"
    demo: lb
  ports:
  - protocol: TCP
    port: 80 #service port
    targetPort: 80
    nodePort: 30007 # Instead of updating sg of node serves with node port's ephemeral port number, we can simply give the node port's port number here.
---
kind: Pod
apiVersion: v1
metadata:
  name: backend-lb 
  labels:
    project: expense
    component: backend
    environment: dev
    version: "1.0.0"
    demo: lb
spec:
  containers:
  - name: nginx
    image: nginx
    