apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: nginx
  # Thse labels are replicaSet labels
  labels:
    app: frontend
    tier: web
spec: 
  # Modify the replicas number according to our use case.
  replicas: 3
  selector:
  # Replicaset use these labels to find the pods for creating desired number of replicas.
    matchLabels:
      app: frontend
      tier: web
  # Pod Template
  template:
    metadata:
      labels: 
        app: frontend
        tier: web
    spec: 
      containers:
      - name: nginx
        image: nginx
