apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  # These labels for deployment resource. 
  labels:
    app: nginx
    tier: frontend
    purpose: deployment
spec: 
  # Modify the replicas number according to our use case.
  replicas: 3
  selector:
  # Replicaset use these labels to find the pods for creating desired number of replicas.
    matchLabels:
      app: nginx
      tier: frontend
      purpose: deployment
  # Pod Template
  template:
    metadata:
      labels: 
        app: nginx
        tier: frontend
        purpose: deployment
    spec: 
      containers:
      - name: nginx
        image: rajavamshi007/deployment:1.0 
        ports:
        - containerPort: 80

---
#Load Balancer to expose our application to the public access.

kind: Service
apiVersion: v1
metadata: 
  name: nginx       
spec: 
  type: LoadBalancer
  selector: #Labels are used as seletors
    app: nginx
    tier: frontend
    purpose: deployment
  ports:
  - protocol: TCP
    port: 80 #service port
    targetPort: 80
    nodePort: 30007 